# Generated by Django 2.0.2 on 2018-03-31 02:44

from django.db import migrations, models
import tokenauth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.CharField(default=tokenauth.models.generate_token, max_length=200, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email', models.CharField(max_length=2000)),
            ],
        ),
    ]
