# Generated by Django 2.0.13 on 2019-11-17 19:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("tokenauth", "0002_authtoken_next_url")]

    operations = [
        migrations.AddField(
            model_name="authtoken",
            name="new_email",
            field=models.CharField(
                blank=True,
                help_text="The email address that the user's email will be set to when they use this token.",
                max_length=2000,
            ),
        )
    ]
