# Generated by Django 3.0.5 on 2021-06-12 12:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("tokenauth", "0003_authtoken_new_email")]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(db_index=True, max_length=2000)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        )
    ]
